version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: fredreis/nginx-fullcycle:prod
    container_name: nginx
    tty: true
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: ./nodejs
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node index.js
    networks:
      - node-network
    volumes:
      - ./nodejs:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
